# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://www.postman.com/downloads/
# https://httpstatuses.com/
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
# https://pl.wikipedia.org/wiki/JSON
# https://bykowski.pl/wp-content/uploads/2017/10/efektywne-rest-api.jpg

###
GET http://127.0.0.1:8000/api/countries
Accept: application/json

###
OPTIONS http://127.0.0.1:8000/api/countries

###
OPTIONS http://127.0.0.1:8000/api/countries/1

###
GET http://127.0.0.1:8000/api/countries/1
Accept: application/json

###
GET http://127.0.0.1:8000/api/trips
Accept: application/json

###
GET http://127.0.0.1:8000/api/trips/1
Accept: application/json

###
POST http://127.0.0.1:8000/api/countries
Accept: application/json
content-type: application/json

{
    "name": "Republika Madagaskaru",
    "code": "MG",
    "currency": "ariary",
    "area": 587041,
    "language": "malgaski"
}

###
PUT http://127.0.0.1:8000/api/countries/13
Accept: application/json
content-type: application/json

{
    "name": "Madagascar",
    "code": "MG",
    "currency": "ariary",
    "area": 587041,
    "language": "francuski"
}

###
DELETE http://127.0.0.1:8000/api/countries/1
Accept: application/json

###
POST http://127.0.0.1:8000/api/trips
Accept: application/json
content-type: application/json

{
    "id": 11,
    "name": "Kolorado 1",
    "continent": "Ameryka Północna 1",
    "period": 7,
    "description": "jest wyżynno-górzystym stanem, którego średnia wysokość nad poziomem morza przekracza 2000 m. Najwyższy szczyt Kolorado, Mount Elbert, wznosi się na 4399 m n.p.m. Zachodnią część stanu zajmują Góry Skaliste i Wyżyna Kolorado, wschodnią – obszar Wielkich Równin.",
    "price": "15000.00",
    "country_id": 2,
    "created_at": "2022-05-12T08:14:10.000000Z",
    "updated_at": "2022-05-12T08:14:10.000000Z"
}

###
PUT http://127.0.0.1:8000/api/trips/11
Accept: application/json
content-type: application/json

{
    "id": 11,
    "name": "Kolorado UPDATE",
    "continent": "Ameryka Północna UPDATE",
    "period": 7,
    "description": "jest wyżynno-górzystym stanem, którego średnia wysokość nad poziomem morza przekracza 2000 m. Najwyższy szczyt Kolorado, Mount Elbert, wznosi się na 4399 m n.p.m. Zachodnią część stanu zajmują Góry Skaliste i Wyżyna Kolorado, wschodnią – obszar Wielkich Równin.",
    "price": "15000.00",
    "country_id": 2,
    "created_at": "2022-05-12T08:14:10.000000Z",
    "updated_at": "2022-05-12T08:14:10.000000Z"
}

###
DELETE http://127.0.0.1:8000/api/trips/11
Accept: application/json


###
GET http://127.0.0.1:8000/api/countries?page=2
Accept: application/json

###
POST http://127.0.0.1:8000/api/trips/bulk
Accept: application/json
content-type: application/json

[
    {
    "name": "Kolorado 03",
    "continent": "Ameryka Północna 1",
    "period": 7,
    "description": "jest wyżynno-górzystym stanem, którego średnia wysokość nad poziomem morza przekracza 2000 m. Najwyższy szczyt Kolorado, Mount Elbert, wznosi się na 4399 m n.p.m. Zachodnią część stanu zajmują Góry Skaliste i Wyżyna Kolorado, wschodnią – obszar Wielkich Równin.",
    "price": "15000.00",
    "country_id": 2,
    "created_at": "2022-05-12T08:14:10",
    "updated_at": "2022-05-12T08:14:10"
},
{
    "name": "Kolorado 02",
    "continent": "Ameryka Północna 2",
    "period": 7,
    "description": "jest wyżynno-górzystym stanem, którego średnia wysokość nad poziomem morza przekracza 2000 m. Najwyższy szczyt Kolorado, Mount Elbert, wznosi się na 4399 m n.p.m. Zachodnią część stanu zajmują Góry Skaliste i Wyżyna Kolorado, wschodnią – obszar Wielkich Równin.",
    "price": "15000.00",
    "country_id": 2,
    "created_at": "2022-05-12T08:14:10",
    "updated_at": "2022-05-12T08:14:10"
}
]